using System;
using System.Data;
using CoreServiceContracts;

namespace CoreServiceContracts.Hub.Holdings
{
#pragma warning disable CS8618
    public class HoldingsDO
    {
        public DateTime? AsOfDate { get; set; }
        public string FundMGG { get; set; }
        public string FundDesc { get; set; }
        public string VPMFund { get; set; }
        public string FundGroup { get; set; }
        public string EntityType { get; set; }
        public string Strategy { get; set; }
        public string VPMCode { get; set; }
        public string BrokerCode { get; set; }
        public string BrokerAccount { get; set; }
        public string BrokerAccountDetails { get; set; }
        public string SecurityDesc { get; set; }
        public string SecurityType { get; set; }
        public string Issuer { get; set; }
        public string IssuerCountry { get; set; }
        public string IssuerIndustry { get; set; }
        public string IssuerCode { get; set; }
        public string PositionCCY { get; set; }
        public string ExposureCCY { get; set; }
        public DateTime? MaturityDate { get; set; }
        public string UltimateIssuer { get; set; }
        public string UltimateDescription { get; set; }
        public DateTime? ContractMaturityDate { get; set; }
        public DateTime? LegalMaturityDate { get; set; }
        public double Multiplier { get; set; }
        public string Currency { get; set; }
        public string AdminCode { get; set; }
        public string FundingStatus { get; set; }
        public bool? NonAccrual { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string CommonName { get; set; }
        public string Borrower { get; set; }
        public string SecurityIRRGrouping { get; set; }
        public string POName { get; set; }
        public string SecurityName { get; set; }
        public string IsFunded { get; set; }
        public string VPMRollUpName { get; set; }
        public double Qty { get; set; }
        public double LocalCost { get; set; }
        public double LocalTotalCost { get; set; }
        public double LocalMarketPrice { get; set; }
        public double LocalMarketValue { get; set; }
        public double FuncCost { get; set; }
        public double FuncTotalCost { get; set; }
        public double FuncMarketPrice { get; set; }
        public double FuncMarketValue { get; set; }
        public double LocalFIAccruedInterest { get; set; }
        public double FuncFIAccruedInterest { get; set; }
        public double LocalAccruedDividends { get; set; }
        public double FuncAccruedDividends { get; set; }
        public double LocalAccruedDivWithholding { get; set; }
        public double FuncAccruedDivWithholding { get; set; }
        public double LocalAccruedDealInterest { get; set; }
        public double FuncAccruedDealInterest { get; set; }
        public double LocalAccruedCashInterest { get; set; }
        public double FuncAccruedCashInterest { get; set; }
        public double AccretedFuncCost { get; set; }
        public double AccretedFuncTotalCost { get; set; }
        public double AccretedLocalCost { get; set; }
        public double AccretedLocalTotalCost { get; set; }
        public double LocalUnRealizedSecInventory { get; set; }
        public double FuncUnRealizedSecInventory { get; set; }
        public double FuncUnRealizedFXInventory { get; set; }
        public double FuncUnRealizedFXInventoryLessContra { get; set; }
        public string SecurityGroup { get; set; }
        public string StrategyGroupCode { get; set; }
        public string StrategyGroupDesc { get; set; }
        public string StrategyCode { get; set; }
        public string StrategyDesc { get; set; }
        public string BrokerDesc { get; set; }
        public int? FundId { get; set; }
        public int? POID { get; set; }
        public int? ProjectID { get; set; }
        public int? FundGroupId { get; set; }
        public int? SymbolId { get; set; }
        public int? BrokerId { get; set; }
        public int? BrokerAccountId { get; set; }
        public int? StrategyId { get; set; }
        public int? RepSecurityTypeID { get; set; }
        public double FuncFundedQty { get; set; }
        public double FuncUnFundedQty { get; set; }
        public double LocalFundedQty { get; set; }
        public double LocalUnFundedQty { get; set; }
        public string Status { get; set; }
        public DateTime? OnDate { get; set; }
        public string RepSecurityType { get; set; }
        public string AssetType { get; set; }
        public string VPMSecType { get; set; }
        public int? ContractId { get; set; }
        public string Facility { get; set; }
        public string ContractCurrency { get; set; }
        public string RateResetFrequency { get; set; }
        public string ContractCode { get; set; }
        public string AccrualMethod { get; set; }
        public string Base { get; set; }
        public double CapRate { get; set; }
        public double CashRate { get; set; }
        public string CouponType { get; set; }
        public double FloorRate { get; set; }
        public double PIKRate { get; set; }
        public string PaymentFrequency { get; set; }
        public double Spread { get; set; }
        public double SpreadAdjustment { get; set; }
        public double CurrentCommitment { get; set; }
        public string ContractType { get; set; }
        public double OriginalAmount { get; set; }
        public string Index { get; set; }
        public double FundingExchangeRate { get; set; }
        public DateTime? FirstPayDate { get; set; }
        public DateTime? IssueDate { get; set; }
        public string UltimateFund { get; set; }
        public int? MGGFundID { get; set; }
        public int? MGGSecurityID { get; set; }
        public string CentaurCode { get; set; }
        public string SSCCode { get; set; }
        public int? PfoCompanyId { get; set; }
        public string PortfolioCompany { get; set; }
        public string CompanyDescription { get; set; }
        public string Ticker { get; set; }
        public string SubIndustry { get; set; }
        public string Industry { get; set; }
        public string IndustryGroup { get; set; }
        public string Sector { get; set; }
        public string InvestmentHoldingFund { get; set; }
        public string ConsolidatedFund { get; set; }
        public string DebtOrEquity { get; set; }
        public string BalanceSheetType { get; set; }
        public string CapitalStack { get; set; }
        public string LienOrderDetail { get; set; }
        public string InstrumentPriming { get; set; }
        public string InstrumentType { get; set; }
        public string NoteType { get; set; }
        public string SecuredStatus { get; set; }
        public string Rating { get; set; }
        public int RowIndex { get; set; }

        public HoldingsDO() { }

        public HoldingsDO(DataRow row)
        {
            AsOfDate = row.Table.Columns.Contains("AsOfDate") ? row["AsOfDate"].ToSafeMinNullDate() : null;
            FundMGG = row.Table.Columns.Contains("Fund (MGG)") ? row["Fund (MGG)"].ToSafeString() : null;
            FundDesc = row.Table.Columns.Contains("FundDescription") ? row["FundDescription"].ToSafeString() : null;
            VPMFund = row.Table.Columns.Contains("Fund") ? row["Fund"].ToSafeString() : null;
            FundGroup = row.Table.Columns.Contains("FundGroup") ? row["FundGroup"].ToSafeString() : null;
            EntityType = row.Table.Columns.Contains("EntityType") ? row["EntityType"].ToSafeString() : null;
            Strategy = row.Table.Columns.Contains("Strategy") ? row["Strategy"].ToSafeString() : null;
            VPMCode = row.Table.Columns.Contains("VPMCode") ? row["VPMCode"].ToSafeString() : null;
            BrokerCode = row.Table.Columns.Contains("BrokerCode") ? row["BrokerCode"].ToSafeString() : null;
            BrokerAccount = row.Table.Columns.Contains("BrokerAccount") ? row["BrokerAccount"].ToSafeString() : null;
            BrokerAccountDetails = row.Table.Columns.Contains("BrokerAccountDetails") ? row["BrokerAccountDetails"].ToSafeString() : null;
            SecurityDesc = row.Table.Columns.Contains("SecurityDescription") ? row["SecurityDescription"].ToSafeString() : null;
            SecurityType = row.Table.Columns.Contains("SecurityType") ? row["SecurityType"].ToSafeString() : null;
            Issuer = row.Table.Columns.Contains("Issuer") ? row["Issuer"].ToSafeString() : null;
            IssuerCountry = row.Table.Columns.Contains("IssuerCountry") ? row["IssuerCountry"].ToSafeString() : null;
            IssuerIndustry = row.Table.Columns.Contains("IssuerIndustry") ? row["IssuerIndustry"].ToSafeString() : null;
            IssuerCode = row.Table.Columns.Contains("IssuerCode") ? row["IssuerCode"].ToSafeString() : null;
            PositionCCY = row.Table.Columns.Contains("Currency") ? row["Currency"].ToSafeString() : null;
            ExposureCCY = row.Table.Columns.Contains("ExposureCCY") ? row["ExposureCCY"].ToSafeString() : null;
            MaturityDate = row.Table.Columns.Contains("MaturityDate") ? row["MaturityDate"].ToSafeMinNullDate() : null;
            UltimateIssuer = row.Table.Columns.Contains("UltimateIssuer") ? row["UltimateIssuer"].ToSafeString() : null;
            UltimateDescription = row.Table.Columns.Contains("UltimateDescription") ? row["UltimateDescription"].ToSafeString() : null;
            ContractMaturityDate = row.Table.Columns.Contains("ContractMaturityDate") ? row["ContractMaturityDate"].ToSafeMinNullDate() : null;
            LegalMaturityDate = row.Table.Columns.Contains("LegalMaturityDate") ? row["LegalMaturityDate"].ToSafeMinNullDate() : null;
            Multiplier = row.Table.Columns.Contains("Multiplier") ? row["Multiplier"].ToSafeDouble() : 0.0;
            Currency = row.Table.Columns.Contains("Currency") ? row["Currency"].ToSafeString() : null;
            AdminCode = row.Table.Columns.Contains("AdminCode") ? row["AdminCode"].ToSafeString() : null;
            FundingStatus = row.Table.Columns.Contains("FundingStatus") ? row["FundingStatus"].ToSafeString() : null;
            NonAccrual = row.Table.Columns.Contains("NonAccrual") ? row["NonAccrual"].ToSafeString().ToSafeBool() : false;
            ProjectName = row.Table.Columns.Contains("ProjectName") ? row["ProjectName"].ToSafeString() : null;
            Description = row.Table.Columns.Contains("Description") ? row["Description"].ToSafeString() : null;
            CommonName = row.Table.Columns.Contains("CommonName") ? row["CommonName"].ToSafeString() : null;
            Borrower = row.Table.Columns.Contains("Borrower") ? row["Borrower"].ToSafeString() : null;
            SecurityIRRGrouping = row.Table.Columns.Contains("SecurityIRRGrouping") ? row["SecurityIRRGrouping"].ToSafeString() : null;
            POName = row.Table.Columns.Contains("POName") ? row["POName"].ToSafeString() : null;
            SecurityName = row.Table.Columns.Contains("SecurityName") ? row["SecurityName"].ToSafeString() : null;
            IsFunded = row.Table.Columns.Contains("IsFunded") ? row["IsFunded"].ToSafeString() : null;
            VPMRollUpName = row.Table.Columns.Contains("VPMRollUpName") ? row["VPMRollUpName"].ToSafeString() : null;
            Qty = row.Table.Columns.Contains("Qty") ? row["Qty"].ToSafeDouble() : 0.0;
            LocalCost = row.Table.Columns.Contains("CostLocal") ? row["CostLocal"].ToSafeDouble() : 0.0;
            LocalTotalCost = row.Table.Columns.Contains("LocalTotalCost") ? row["LocalTotalCost"].ToSafeDouble() : 0.0;
            LocalMarketPrice = row.Table.Columns.Contains("LocalMarketPrice") ? row["LocalMarketPrice"].ToSafeDouble() : 0.0;
            LocalMarketValue = row.Table.Columns.Contains("MVGrossLocal") ? row["MVGrossLocal"].ToSafeDouble() : 0.0;
            FuncCost = row.Table.Columns.Contains("CostUSD") ? row["CostUSD"].ToSafeDouble() : 0.0;
            FuncTotalCost = row.Table.Columns.Contains("FuncTotalCost") ? row["FuncTotalCost"].ToSafeDouble() : 0.0;
            FuncMarketPrice = row.Table.Columns.Contains("FuncMarketPrice") ? row["FuncMarketPrice"].ToSafeDouble() : 0.0;
            FuncMarketValue = row.Table.Columns.Contains("MVGrossUSD") ? row["MVGrossUSD"].ToSafeDouble() : 0.0;
            FuncFundedQty = row.Table.Columns.Contains("FundedAmountUSD") ? row["FundedAmountUSD"].ToSafeDouble() : 0.0;
            FuncUnFundedQty = row.Table.Columns.Contains("UnfundedAmountUSD") ? row["UnfundedAmountUSD"].ToSafeDouble() : 0.0;
            LocalFundedQty = row.Table.Columns.Contains("FundedAmount") ? row["FundedAmount"].ToSafeDouble() : 0.0;
            LocalUnFundedQty = row.Table.Columns.Contains("UnFundedAmount") ? row["UnFundedAmount"].ToSafeDouble() : 0.0;
            FundId = row.Table.Columns.Contains("FundID") ? row["FundID"].ToSafeString().ToSafeInt() : (int?)null;
            SymbolId = row.Table.Columns.Contains("SymbolID") ? row["SymbolID"].ToSafeString().ToSafeInt() : (int?)null;
            BrokerId = row.Table.Columns.Contains("BrokerId") ? row["BrokerId"].ToSafeString().ToSafeInt() : (int?)null;
            BrokerAccountId = row.Table.Columns.Contains("BrokerAccountId") ? row["BrokerAccountId"].ToSafeString().ToSafeInt() : (int?)null;
            StrategyId = row.Table.Columns.Contains("StrategyId") ? row["StrategyId"].ToSafeString().ToSafeInt() : (int?)null;
            ProjectID = row.Table.Columns.Contains("ProjectID") ? row["ProjectID"].ToSafeString().ToSafeInt() : (int?)null;
            ContractId = row.Table.Columns.Contains("ContractId") ? row["ContractId"].ToSafeString().ToSafeInt() : (int?)null;
            MGGFundID = row.Table.Columns.Contains("MGGFundID") ? row["MGGFundID"].ToSafeString().ToSafeInt() : (int?)null;
            MGGSecurityID = row.Table.Columns.Contains("MGGSecurityID") ? row["MGGSecurityID"].ToSafeString().ToSafeInt() : (int?)null;
            PfoCompanyId = row.Table.Columns.Contains("PfoCompanyId") ? row["PfoCompanyId"].ToSafeString().ToSafeInt() : (int?)null;
            FundGroupId = row.Table.Columns.Contains("FundGroupId") ? row["FundGroupId"].ToSafeString().ToSafeInt() : (int?)null;
            AssetType = row.Table.Columns.Contains("AssetType") ? row["AssetType"].ToSafeString() : null;
            RepSecurityType = row.Table.Columns.Contains("RepSecurityType") ? row["RepSecurityType"].ToSafeString() : null;
            DebtOrEquity = row.Table.Columns.Contains("DebtOrEquity") ? row["DebtOrEquity"].ToSafeString() : null;
            BalanceSheetType = row.Table.Columns.Contains("BalanceSheetType") ? row["BalanceSheetType"].ToSafeString() : null;
            CapitalStack = row.Table.Columns.Contains("CapitalStack") ? row["CapitalStack"].ToSafeString() : null;
            LienOrderDetail = row.Table.Columns.Contains("LienOrderDetail") ? row["LienOrderDetail"].ToSafeString() : null;
            InstrumentPriming = row.Table.Columns.Contains("InstrumentPriming") ? row["InstrumentPriming"].ToSafeString() : null;
            InstrumentType = row.Table.Columns.Contains("InstrumentType") ? row["InstrumentType"].ToSafeString() : null;
            NoteType = row.Table.Columns.Contains("NoteType") ? row["NoteType"].ToSafeString() : null;
            SecuredStatus = row.Table.Columns.Contains("SecuredStatus") ? row["SecuredStatus"].ToSafeString() : null;
            Rating = row.Table.Columns.Contains("Rating") ? row["Rating"].ToSafeString() : null;
            CapRate = row.Table.Columns.Contains("CapRate") ? row["CapRate"].ToSafeDouble() : 0.0;
            CashRate = row.Table.Columns.Contains("CashRate") ? row["CashRate"].ToSafeDouble() : 0.0;
            FloorRate = row.Table.Columns.Contains("FloorRate") ? row["FloorRate"].ToSafeDouble() : 0.0;
            PIKRate = row.Table.Columns.Contains("PIKRate") ? row["PIKRate"].ToSafeDouble() : 0.0;
            Spread = row.Table.Columns.Contains("Spread") ? row["Spread"].ToSafeDouble() : 0.0;
            SpreadAdjustment = row.Table.Columns.Contains("SpreadAdjustment") ? row["SpreadAdjustment"].ToSafeDouble() : 0.0;
            CurrentCommitment = row.Table.Columns.Contains("CurrentCommitment") ? row["CurrentCommitment"].ToSafeDouble() : 0.0;
            OriginalAmount = row.Table.Columns.Contains("OriginalAmount") ? row["OriginalAmount"].ToSafeDouble() : 0.0;
            FundingExchangeRate = row.Table.Columns.Contains("FundingExchangeRate") ? row["FundingExchangeRate"].ToSafeDouble() : 0.0;
            FirstPayDate = row.Table.Columns.Contains("FirstPayDate") ? row["FirstPayDate"].ToSafeMinNullDate() : null;
            IssueDate = row.Table.Columns.Contains("IssueDate") ? row["IssueDate"].ToSafeMinNullDate() : null;
            RowIndex = row.Table.Columns.Contains("RowIndex") ? row["RowIndex"].ToSafeInt() : 0;
        }


    }
#pragma warning restore CS8618
}